// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yptbyrnzfdgtwithckma.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlwdGJ5cm56ZmRndHdpdGhja21hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY0MzU4MTcsImV4cCI6MjA2MjAxMTgxN30.WdslXMgc_iUDyCAceb5uECaiIacAtKy8QyHoEdYtP3k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);